### ISSUE TITLE
Document known limitations/deficiencies for production readiness.

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/dcos-jenkins-service#15]
As a datacenter operator it would be nice to know what are the current limitations with the Jenkins on Mesos framework.

For instance, the Jenkins on Mesos scheduler does not perform task reconciliation at this time (12/28/2015)

It would be nice to understand what features would need to be implemented before jenkins-mesos can be considered a production-ready Mesos Scheduler/Framework.

**Comment by micahlmartin** [comment]
:+1: on this. What do you mean by "task reconciliation"?

**Comment by ssk2** [comment]
@micahlmartin - when the Jenkins framework goes away (if Jenkins is restarted or the task dies), it is currently unable to reconcile running builds. This behaves in the same way as ordinary Jenkins (i.e. your in-progress builds will be lost). Usually it's not a problem if you do a safe restart but may be an issue if you do an upgrade or the Jenkins master dies. 

Many Mesos frameworks, particularly that run long running tasks, will reconcile their list of of tasks against what's running. The Jenkins plugin doesn't offer this functionality because builds are ephemeral and will terminate of their own accord. When running long-running services, if you don't reconcile tasks, there's a danger they'll be orphaned and run forever!

**Comment by nrshrivatsan** [comment]
![screen shot 2016-08-22 at 2 27 45 pm](https://cloud.githubusercontent.com/assets/5283109/17872387/a497e546-6874-11e6-8846-de6d2ce6718c.png)

I couldn't find any `apt-get` or `dpkg -i` to get the mesos.so into the Jenkins Master in the [Dockerfile](https://github.com/mesosphere/jenkins-dcos/blob/master/Dockerfile)

Could you shed some light on these lines too, as a part of the documentation?

**Comment by ssk2** [comment]
@nrshrivatsan: sure. It looks like your screenshot has been customised. We set the default to `/opt/mesosphere/lib/libmesos.so` (see https://github.com/mesosphere/jenkins-dcos/blob/master/conf/jenkins/config.xml#L21), which is mounted in from the host operating system (see https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/J/jenkins/11/marathon.json.mustache#L36).

**Comment by ssk2** [comment]
[Moved to JIRA](https://jira.mesosphere.com/browse/JENKINS-138).
